### ISSUE TITLE
1.20 upgrade requirement - coreDNS 1.8.3 RBAC updates required

### ISSUE THREAD

**Issue by dan-slinky-ckpd** [cookpad/terraform-aws-eks#211]
When upgrading coreDNS to 1.8.3 as part of an upgrade from 1.19 to 1.20, there is/was an undocumented update required to the cluster role.

Error observed

```
pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.EndpointSlice: failed to list *v1beta1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
```

`system:coredns` will need the following clusterole updated with

```
- apiGroups:
   - discovery.k8s.io
   resources:
   - endpointslices
   verbs:
   - list
   - watch
```

The manifests in the addons directory will need be updated.
