### ISSUE TITLE
Possible regression of #209 in 1.20

### ISSUE THREAD

**Issue by ettiee** [cookpad/terraform-aws-eks#285]
We updated kube-proxy to configure `bindAddress: 127.0.0.1` in https://github.com/cookpad/terraform-aws-eks/pull/209
There's an alternative workaround suggested https://github.com/aws/amazon-vpc-cni-k8s/issues/1702#issuecomment-958003889 to include the following configuration for `kube-proxy`:

```
spec:
  template:
    spec:
      containers:
        - name: kube-proxy
          command:
            - kube-proxy
            - --hostname-override=$(NODE_NAME)
            - --v=2
            - --config=/var/lib/kube-proxy-config/config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
```

[hostnameOverride](https://github.com/kubernetes/kube-proxy/blob/1ba80d723ecf0de5bd3e0fd4ef57d1c56e9ea1c0/config/v1alpha1/types.go#L129) is another way to override kube-proxy behaviour and explicitly pass a host, not waiting for the node IP. 

Because we moved to eks managed addons in https://github.com/cookpad/terraform-aws-eks/pull/276/commits/c35b736ed8ea771d610e02a49dce4dac566632d9 this will not include either of the recommended workarounds ( bindAddress: 127.0.0.1` or --hostname-override=$(NODE_NAME) )

The EKS addons maintainers are going to provide `--hostname-override`  in eks addons but [haven't done it by default yet](https://github.com/aws/amazon-vpc-cni-k8s/issues/1702#issuecomment-953094651), and we can't override configuration in the [terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon).
